In [3]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
import os

In [4]:
def get_file(path):
    with open(path, 'r') as f:
        contents = f.read()
    soup = BeautifulSoup(contents, 'lxml')
    soup_body = str(soup.body)
    return soup_body

In [5]:
def women_men_games(event, paths, df):
    soup_body = get_file(paths)
    pattern_country = r'<div class="playerTag" country="(.*)" register='
    pattern_name = r'<td data-sort="(.*)">'
    pattern_time = r'</span></a></div></div></td>\n<td class="text-right">\n(.*)'
    pattern_helmet = r'<td class="text-right d-none d-md-table-cell">\n(.*)</td>'
    pattern_group = r'splitContentResult-STK(.*)" role="row"'
    pattern_rank = r'<td class="text-right sorting_1" data-sort="(.*)">'
    pattern_Q_q = r'<td class="text-right">\n([\s\S]*?)\n</td>\n<td class="text-center d-none d-md-table-cell">'

    country = re.findall(pattern_country,soup_body)
    name = re.findall(pattern_name,soup_body)
    time = re.findall(pattern_time,soup_body)
    helmet = re.findall(pattern_helmet,soup_body)
    group_info =  re.findall(pattern_group,soup_body)
    rank =  re.findall(pattern_rank,soup_body)
    qualified = re.findall(pattern_Q_q,soup_body)

    time = [i.replace('</td>', '').strip() if 'td' in i else 'No Time' if 'No Time' in i else i for i in time]

    helmet = [int(i.strip()) for i in helmet]

    country = country[2:]

    group = [i[i.index(event)+len(event):i.index(event)+len(event)+7] for i in group_info]
    
    game_name = [i[:i.index(event)+len(event)].replace('-', ' ') for i in group_info]

    qualified = [re.findall(r'">(.*)</abbr></strong>',i)  for i in qualified]
    
    
    df['country'] = country
    df['helmet_number'] = helmet
    df['name'] = name
    df['group'] = group
    df['game'] = game_name
    df['rank'] = rank
    df['time'] = time
    df['qualified'] = qualified
    return df

In [6]:
list_files = list(os.listdir('Html_files'))

In [7]:
list_files = ['Html_files/' + i for i in list_files]

In [8]:
df_W500_sfnl = pd.DataFrame()
df_M1000_heat = pd.DataFrame()
df_M500_qfnl = pd.DataFrame()
df_M1000_fnl = pd.DataFrame()
df_M500_heat = pd.DataFrame()
df_M1000_qfnl = pd.DataFrame()
df_W1000_sfnl = pd.DataFrame()
df_M500_fnl = pd.DataFrame()
df_W1000_qfnl = pd.DataFrame()
df_W500_fnl = pd.DataFrame()
df_M500_sfnl = pd.DataFrame()
df_W500_heat = pd.DataFrame()
df_W500_qfnl = pd.DataFrame()
df_M1000_sfnl = pd.DataFrame()
df_W1000_heat = pd.DataFrame()
df_W1000_fnl = pd.DataFrame()
df_M1500_qfnl = pd.DataFrame()
df_W1500_sfnl = pd.DataFrame()
df_M5000R_fnl = pd.DataFrame()
df_MixR_sfnl = pd.DataFrame()
df_W3000R_fnl = pd.DataFrame()
df_M1500_fnl = pd.DataFrame()
df_W1500_fnl = pd.DataFrame()
df_MixR_fnl = pd.DataFrame()
df_W3000R_sfnl = pd.DataFrame()
df_M1500_sfnl = pd.DataFrame()
df_W1500_qfnl = pd.DataFrame()
df_M5000R_sfnl = pd.DataFrame()
df_MixR_qfnl = pd.DataFrame()

In [9]:
list_df = [
    df_W500_sfnl,
    df_M1000_heat,
    df_M500_qfnl,
    df_M1000_fnl,
    df_M500_heat,
    df_M1000_qfnl,
    df_W1000_sfnl,
    df_M500_fnl,
    df_W1000_qfnl,
    df_W500_fnl,
    df_M500_sfnl,
    df_W500_heat,
    df_W500_qfnl,
    df_M1000_sfnl,
    df_W1000_heat,
    df_W1000_fnl,
    df_M1500_qfnl,
    df_W1500_sfnl,
    df_M1500_fnl,
    df_W1500_fnl,
    df_M1500_sfnl,
    df_W1500_qfnl,
]

list_relay_df = [
    df_M5000R_fnl,
    df_MixR_sfnl,
    df_W3000R_fnl,
    df_MixR_fnl,
    df_W3000R_sfnl,
    df_M5000R_sfnl,
    df_MixR_qfnl
]

In [10]:
list_event = [
'SFNL',
'HEAT',
'QFNL',
'FNL',
'HEAT',
'QFNL',
'SFNL',
'FNL',
'QFNL',
'FNL',
'SFNL',
'HEAT',
'QFNL',
'SFNL',
'HEAT',
'FNL',
'QFNL',
'SFNL',
'FNL',
'FNL',
'SFNL',
'QFNL',
]

list_relay_event = [
    'FNL',
    'SFNL',
    'FNL',
    'FNL',
    'SFNL',
    'SFNL',
    'QFNL']

In [11]:
list_files.remove("Html_files/Men's 5000m Relay - Finals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Mixed Team Relay - Semifinals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Women's 3000m Relay - Finals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Mixed Team Relay - Finals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Women's 3000m Relay - Semifinals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Men's 5000m Relay - Semifinals Results - Olympic Short Track Speed Skating.html")
list_files.remove("Html_files/Mixed Team Relay - Quarterfinals Results - Olympic Short Track Speed Skating.html")

list_relay_files = ["Html_files/Men's 5000m Relay - Finals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Mixed Team Relay - Semifinals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Women's 3000m Relay - Finals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Mixed Team Relay - Finals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Women's 3000m Relay - Semifinals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Men's 5000m Relay - Semifinals Results - Olympic Short Track Speed Skating.html",
             "Html_files/Mixed Team Relay - Quarterfinals Results - Olympic Short Track Speed Skating.html"]

In [12]:
for i,df in enumerate(list_df):
    df = women_men_games(list_event[i], list_files[i],df)

In [13]:
def relay(event, paths, df):
    soup_body = get_file(paths)
    pattern_country = r'<td class="text-right" data-sort="(.*)">\n<div'
    pattern_name = r'<td data-sort="(.*)">'
    pattern_time = r'</a></div></div></td>\n<td class="text-right">\n(.*)'
    pattern_group = r'splitContentResult-STK(.*)" role="row"'
    pattern_rank = r'<td class="text-right sorting_1" data-sort="(.*)">'
    pattern_Q_q = r'<td class="text-right">\n([\s\S]*?)\n</td>\n<td class="text-center d-none d-md-table-cell">'

    country = re.findall(pattern_country,soup_body)
    name = re.findall(pattern_name,soup_body)
    time = re.findall(pattern_time,soup_body)
    group_info =  re.findall(pattern_group,soup_body)
    rank =  re.findall(pattern_rank,soup_body)
    qualified = re.findall(pattern_Q_q,soup_body)
    
    time = [i.replace('</td>', '').strip() if 'td' in i else 'No Time' if 'No Time' in i else i for i in time]

    group = [i[i.index(event)+len(event):i.index(event)+len(event)+6] for i in group_info]
    
    game_name = [i[:i.index(event)+len(event)].replace('-', ' ') for i in group_info]


    qualified = [re.findall(r'">(.*)</abbr></strong>',i)  for i in qualified]


    df['country'] = country
    df['name'] = name
    df['group'] = group
    df['group_name'] = game_name
    df['rank'] = rank
    df['time'] = time
    df['qualified'] = qualified

In [14]:
for i,df in enumerate(list_relay_df):
    df = relay(list_relay_event[i], list_relay_files[i],df)

In [15]:
def concat(df,list_):
    for i in list_:
        df = df.append(i)
    list_time = []
    for count, time in enumerate(df['time']):
        if '>' in time:
            list_time.append(re.findall(r'>(.*)</abbr>', time)[0])
        else:
            list_time.append(time)
    df['time'] = list_time
    return df

In [16]:
df_w_m_game = pd.DataFrame()
df_w_m_game = concat(df_w_m_game, list_df)

In [17]:
df_relay_game = pd.DataFrame()
df_relay_game = concat(df_relay_game, list_relay_df)

In [18]:
df_w_m_game

,country,helmet_number,name,group,game,rank,time,qualified
0,ITA,3,FONTANA Arianna,000100-,W500M SFNL,1,42.387,[QA]
1,CAN,35,BOUTIN Kim,000100-,W500M SFNL,2,42.664,[QA]
2,ROC,141,SEREGINA Elena,000100-,W500M SFNL,3,42.685,[QB]
3,CAN,50,CHARLES Alyson,000100-,W500M SFNL,4,42.829,[QB]
4,ITA,97,VALCEPINA Arianna,000100-,W500M SFNL,5,44.044,[]
...,...,...,...,...,...,...,...,...
31,BEL,5,DESMET Hanne,000600-,W1500M QFNL,2,2:18.931,[Q]
32,ROC,7,PROSVIRNOVA Sofia,000600-,W1500M QFNL,3,2:19.432,[Q]
33,CHN,42,ZHANG Chutong,000600-,W1500M QFNL,4,2:19.839,[q]
34,POL,16,MALISZEWSKA Natalia,000600-,W1500M QFNL,5,2:25.850,[]
35,ROC,9,EFREMENKOVA Ekaterina,000600-,W1500M QFNL,6,No Time,[]

In [19]:
df_relay_game

,country,name,group,group_name,rank,time,qualified
0,CAN,Canada,-A0010,M5000MRY4 FNL,1,6:41.257,[]
1,KOR,Republic of Korea,-A0010,M5000MRY4 FNL,2,6:41.679,[]
2,ITA,Italy,-A0010,M5000MRY4 FNL,3,6:43.431,[]
3,ROC,ROC,-A0010,M5000MRY4 FNL,4,6:43.440,[]
4,CHN,People's Republic of China,-A0010,M5000MRY4 FNL,5,6:51.654,[]
5,HUN,Hungary,-B0010,M5000MRY4 FNL,1,6:39.713,[]
6,NED,Netherlands,-B0010,M5000MRY4 FNL,2,6:39.780,[]
7,JPN,Japan,-B0010,M5000MRY4 FNL,3,6:40.545,[]
0,CAN,Canada,000100,XRELAY4 SFNL,1,2:36.808,[QA]
1,ITA,Italy,000100,XRELAY4 SFNL,2,2:36.895,[QA]
2,KAZ,Kazakhstan,000100,XRELAY4 SFNL,3,2:42.575,[QB]
3,NED,Netherlands,000100,XRELAY4 SFNL,4,2:51.919,[QB]
4,HUN,Hungary,000200,XRELAY4 SFNL,1,2:38.052,[QA]
5,CHN,People's Republic of China,000200,XRELAY4 SFNL,2,2:38.783,[QA]
6,ROC,ROC,000200,XRELAY4 SFNL,3,PEN,[]
7,USA,United States of America,000200,XRELAY4 SFNL,4,PEN,[]
0,NED,Netherlands,-A0010,W3000MRY4 FNL,1,4:03.409,[OR]
1,KOR,Republic of Korea,-A0010,W3000MRY4 FNL,2,4:03.627,[]
2,CHN,People's Republic of China,-A0010,W3000MRY4 FNL,3,4:03.863,[]
3,CAN,Canada,-A0010,W3000MRY4 FNL,4,4:04.329,[]
4,ITA,Italy,-B0010,W3000MRY4 FNL,1,4:09.688,[]
5,POL,Poland,-B0010,W3000MRY4 FNL,2,4:10.210,[]
6,ROC,ROC,-B0010,W3000MRY4 FNL,3,PEN,[]
7,USA,United States of America,-B0010,W3000MRY4 FNL,4,PEN,[]
0,CHN,People's Republic of China,-A0010,XRELAY4 FNL,1,2:37.348,[]
1,ITA,Italy,-A0010,XRELAY4 FNL,2,2:37.364,[]
2,HUN,Hungary,-A0010,XRELAY4 FNL,3,2:40.900,[]
3,CAN,Canada,-A0010,XRELAY4 FNL,4,PEN,[]
4,NED,Netherlands,-B0010,XRELAY4 FNL,1,2:36.966,[]
5,KAZ,Kazakhstan,-B0010,XRELAY4 FNL,2,2:44.148,[]
0,NED,Netherlands,000100,W3000MRY4 SFNL,1,4:04.133,[QA]
1,CHN,People's Republic of China,000100,W3000MRY4 SFNL,2,4:04.383,[QA]
2,POL,Poland,000100,W3000MRY4 SFNL,3,4:10.074,[QB]
3,ITA,Italy,000100,W3000MRY4 SFNL,4,4:17.438,[QB]
4,CAN,Canada,000200,W3000MRY4 SFNL,1,4:05.893,[QA]
5,KOR,Republic of Korea,000200,W3000MRY4 SFNL,2,4:05.904,[QA]
6,ROC,ROC,000200,W3000MRY4 SFNL,3,4:06.064,[QB]
7,USA,United States of America,000200,W3000MRY4 SFNL,4,4:06.098,[QB]
0,CAN,Canada,000100,M5000MRY4 SFNL,1,6:38.752,[QA]
1,ITA,Italy,000100,M5000MRY4 SFNL,2,6:38.899,[QA]
2,JPN,Japan,000100,M5000MRY4 SFNL,3,6:40.446,[QB]
3,CHN,People's Republic of China,000100,M5000MRY4 SFNL,4,6:51.040,[ADVA]
4,KOR,Republic of Korea,000200,M5000MRY4 SFNL,1,6:37.879,[QA]
5,ROC,ROC,000200,M5000MRY4 SFNL,2,6:37.925,[QA]
6,NED,Netherlands,000200,M5000MRY4 SFNL,3,6:37.927,[QB]
7,HUN,Hungary,000200,M5000MRY4 SFNL,4,6:45.172,[QB]
0,CHN,People's Republic of China,000100,XRELAY4 QFNL,1,2:37.535,[Q]
1,ITA,Italy,000100,XRELAY4 QFNL,2,2:38.308,[Q]
2,KOR,Republic of Korea,000100,XRELAY4 QFNL,3,2:48.308,[]
3,POL,Poland,000100,XRELAY4 QFNL,4,2:50.513,[]
4,NED,Netherlands,000200,XRELAY4 QFNL,1,2:36.437,"[OR, Q]"
5,CAN,Canada,000200,XRELAY4 QFNL,2,2:36.747,[Q]
6,KAZ,Kazakhstan,000200,XRELAY4 QFNL,3,2:43.004,[q]
7,FRA,France,000200,XRELAY4 QFNL,4,2:51.221,[]
8,HUN,Hungary,000300,XRELAY4 QFNL,1,2:38.396,[Q]
9,ROC,ROC,000300,XRELAY4 QFNL,2,2:38.445,[Q]
10,USA,United States of America,000300,XRELAY4 QFNL,3,2:39.043,[q]
11,JPN,Japan,000300,XRELAY4 QFNL,4,2:39.112,[]